### ISSUE TITLE
Eric's Imba 2 Feature Discussions in one place with links

### ISSUE THREAD

**Issue by ericvida** [imba/imba#332]
Here is a summary of the discussions I'm most interested in, in somewhat of an order of personal importance for your evaluation and discussion.

- [x] support for pseudo classes .sm:font-small,
possibly change :click to @click so there is no conflict https://github.com/imba/imba/issues/326

- [ ] Embedding expressions in Template Literals `${}` https://github.com/imba/imba/issues/319

- [x] String line syntax. `<div> | hello {name}` https://github.com/imba/imba/issues/198

- [x] Unique ID (ref) for any DOM element https://github.com/imba/imba/issues/330

- [ ] Unique ID (ref) used for scoped css https://github.com/imba/imba/issues/325

- [ ] Add classes to element from outside the tag. 
https://users.imba.io/t/element-classes-feature/85
Related: Setting flags from outside render:  https://github.com/imba/imba/issues/286

### CSS in Imba
Fixing template literal Embedded Expressions https://github.com/imba/imba/issues/319 is a good temporary alternative.
As template literals can be used for dynamic CSS.
Here's a very satisfying solution: https://scrimba.com/c/cmmkKaS9
Used in conjunction with CSS variables and comment blocks, it's pretty pretty powerful.
Here are some other discussions about CSS in Imba:

- [ ] Scoped css tag `<styles css scoped>` https://github.com/imba/imba/issues/312#issuecomment-597813688

- [ ] Css in Imba with Alteo https://github.com/imba/imba/issues/303

- [ ] CSS block scoped based on indentation, using unique ID's or Refs for scoped css https://github.com/imba/imba/issues/325 https://github.com/imba/imba/issues/330
